### ISSUE TITLE
when run the test,there will be segment fault appear.

### ISSUE THREAD

**Issue by jinqingqing** [jinqingqing/mini_crt#1]
gdb -c core.15284 ./test 
GNU gdb Fedora (6.8-29.fc10) Copyright (C) 2008 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.  Type "show copying" and "show warranty" for details. This GDB was configured as "i386-redhat-linux-gnu"... Core was generated by `./test art hello 111'. Program terminated with signal 11, Segmentation fault. [New process 15284] #0  0x08048c72 in strlen ()
 (gdb) bt
 #0  0x08048c72 in strlen () 
#1  0x0804860a in fputs ()
#2  0x08048791 in vfprintf () 
#3  0x0804885b in printf () 
#4  0x080482f2 in main (argc=4, argv=0xbfa95a24) at test.c:35 (gdb)

**Comment by jinqingqing** [comment]
1. it is not easy to find the problem directly.
2.the method can be taken is to use gdb.
3.how to use the gdb.
